### 1. **Array Creation and Manipulation**
   - np.array(): Create an array from a list or other data structures.
   - np.arange(): Create an array with a range of values (like range() in Python).
   - np.linspace(): Create an array of evenly spaced values over a specified range.
   - np.zeros(): Create an array filled with zeros.
   - np.ones(): Create an array filled with ones.
   - np.empty(): Create an uninitialized array.
   - np.eye(): Create a 2D identity matrix.
   - np.full(): Create an array filled with a constant value.
   - np.reshape(): Change the shape of an array.
   - np.ravel(): Flatten an array into one dimension.
   - np.concatenate(): Join two or more arrays.
   - np.split(): Split an array into multiple sub-arrays.
   - np.vstack(): Stack arrays in sequence vertically (row wise).
   - np.hstack(): Stack arrays in sequence horizontally (column wise).

### 2. **Array Operations**
   - np.add(): Element-wise addition of arrays.
   - np.subtract(): Element-wise subtraction of arrays.
   - np.multiply(): Element-wise multiplication of arrays.
   - np.divide(): Element-wise division of arrays.
   - np.power(): Element-wise exponentiation.
   - np.mod(): Element-wise modulus operation.
   - np.dot(): Dot product of two arrays.
   - np.cross(): Cross product of two vectors.
   - np.matmul(): Matrix multiplication (for higher dimensions too).
   - np.sum(): Sum of array elements.
   - np.prod(): Product of array elements.
   - np.cumsum(): Cumulative sum of array elements.
   - np.cumprod(): Cumulative product of array elements.
   - np.mean(): Mean of array elements.
   - np.median(): Median of array elements.
   - np.std(): Standard deviation of array elements.
   - np.var(): Variance of array elements.
   - np.min(): Minimum value in an array.
   - np.max(): Maximum value in an array.
   - np.argmin(): Index of the minimum value.
   - np.argmax(): Index of the maximum value.
   - np.ptp(): Peak-to-peak (difference between max and min).
   - np.sort(): Sort array elements.
   - np.argsort(): Indices that would sort the array.
   - np.unique(): Find unique elements in an array.

### 3. **Mathematical and Statistical Functions**
   - np.sin(), np.cos(), np.tan(): Trigonometric functions.
   - np.sinh(), np.cosh(), np.tanh(): Hyperbolic trigonometric functions.
   - np.exp(): Exponential function.
   - np.log(), np.log10(), np.log2(): Logarithmic functions.
   - np.sqrt(): Square root.
   - np.abs(): Absolute value.
   - np.round(): Round array elements.
   - np.floor(): Floor function (round down).
   - np.ceil(): Ceiling function (round up).
   - np.isclose(): Element-wise comparison for closeness.
   - np.sign(): Sign of elements.

### 4. **Linear Algebra**
   - np.linalg.inv(): Inverse of a matrix.
   - np.linalg.det(): Determinant of a matrix.
   - np.linalg.eig(): Eigenvalues and eigenvectors.
   - np.linalg.svd(): Singular Value Decomposition (SVD).
   - np.linalg.norm(): Norm of a vector or matrix.
   - np.linalg.solve(): Solve a system of linear equations.
   - np.linalg.matrix_rank(): Rank of a matrix.
   - np.linalg.cholesky(): Cholesky decomposition.

### 5. **Random Module**
   - np.random.rand(): Generate random numbers from a uniform distribution.
   - np.random.randn(): Generate random numbers from a standard normal distribution.
   - np.random.randint(): Generate random integers.
   - np.random.choice(): Randomly choose elements from an array.
   - np.random.shuffle(): Shuffle array elements in place.
   - np.random.seed(): Set the seed for random number generation.

### 6. **Broadcasting and Indexing**
   - np.where(): Return elements chosen from x or y depending on a condition.
   - np.nonzero(): Return indices of non-zero elements.
   - np.take(): Take elements from an array along a specific axis.
   - np.put(): Put values into an array at specified indices.
   - np.flatten(): Flatten the array.
   - np.transpose(): Transpose the dimensions of an array.

### 7. **I/O Operations**
   - np.loadtxt(): Load data from a text file.
   - np.savetxt(): Save data to a text file.
   - np.load(): Load an array from a binary file.
   - np.save(): Save an array to a binary file.
   - np.genfromtxt(): Load data with missing values from a text file.
   - np.savez(): Save multiple arrays into a .npz file (compressed format).

### 8. **Set Operations**
   - np.union1d(): Find the union of two arrays.
   - np.intersect1d(): Find the intersection of two arrays.
   - np.setdiff1d(): Find the difference between two arrays.
   - np.setxor1d(): Find the symmetric difference between two arrays.

### 9. **Advanced Functions**
   - np.gradient(): Compute the gradient of an array.
   - np.diff(): Compute the difference between consecutive elements.
   - np.histogram(): Compute the histogram of an array.
   - np.corrcoef(): Compute the correlation coefficient.
   - np.polyfit(): Least squares polynomial fit.
   - np.fft.fft(): Compute the one-dimensional discrete Fourier Transform.
   - np.fft.ifft(): Compute the inverse of the discrete Fourier Transform.

### 10. **Data Type and Shape Manipulation**
   - np.astype(): Change the data type of an array.
   - np.size(): Return the total number of elements in an array.
   - np.shape(): Return the shape (dimensions) of an array.
   - np.ndim(): Return the number of dimensions of an array.
   - np.item(): Return a specific item from an array.

### 11. **Element-wise Comparison and Logical Operations**
   - np.equal(): Element-wise comparison for equality.
   - np.not_equal(): Element-wise comparison for inequality.
   - np.less(): Element-wise comparison for less than.
   - np.less_equal(): Element-wise comparison for less than or equal.
   - np.greater(): Element-wise comparison for greater than.
   - np.greater_equal(): Element-wise comparison for greater than or equal.
   - np.logical_and(): Element-wise logical AND.
   - np.logical_or(): Element-wise logical OR.
   - np.logical_not(): Element-wise logical NOT.
   - np.any(): Check if any element is true.
   - np.all(): Check if all elements are true.

In [1]:
import numpy as np
lis=[10,20,30,40,50]
arr=np.array(lis)
z=arr[2]
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
# sequence of the promotion in bool → int8, uint8 → int16, uint16 → int32, uint32 → int64, uint64 → float16 → float32 → float64 → complex64 → complex128
# to find data type of the given numpy value use (variable_name).dtype
import numpy as np
arr=np.array([20,30,40,50,32.54])
arr1=np.array([10,20,40,-15,25])
arr2=np.array([12,15,17,30,23,35])
print(arr.dtype)
print(arr1.dtype)
print(arr2.dtype)

float64
int32
int32


In [3]:
# Size is the optional may we declare the values directly
import numpy as np
import random
# Generating the 0-d array
random_0d=np.random.randint(0,4,size=(1,1))
print(f'''This will print 0-D array:
{random_0d}
''')
random_1d=np.random.randint(6,size=(6))
print(f'''This will print 1-D array:
{random_1d}
''')
# Generating the 2d array
random_2d=np.random.randint(5,10,size=(3,4))
print(f'''that it will print the 3-rows and 4 coloums 3*4:
{random_2d}
''')
# Generating the 3d array
random_3d=np.random.randint(0,2,size=(4,3,3))
print(f'''it generate 4,3*3 arrays
{random_3d}''')

This will print 0-D array:
[[1]]

This will print 1-D array:
[4 5 0 1 0 1]

that it will print the 3-rows and 4 coloums 3*4:
[[9 8 6 7]
 [8 6 6 8]
 [8 9 8 6]]

it generate 4,3*3 arrays
[[[0 1 0]
  [0 1 0]
  [1 1 1]]

 [[0 1 1]
  [0 1 1]
  [1 1 0]]

 [[1 0 0]
  [0 1 0]
  [0 1 1]]

 [[1 0 1]
  [0 0 0]
  [0 0 1]]]


In [4]:
# ndim is a function is numpy function which is used to tell abpout the number of dimensions that the array contain
print(random_2d.ndim)
print(random_3d.ndim)

2
3


In [6]:
import random
lis=[10,20,30,45,23,45,56,23,45,12,34,5]
# To covert the given list into the ndarray we use reshape function it will convert it
arr=np.array(lis)
re_arr=arr.reshape(3,4)
print(re_arr)

[[10 20 30 45]
 [23 45 56 23]
 [45 12 34  5]]


In [10]:
# variable.shape is the bulid-in function in the np which is used to know the no.of rows and coloums in the array if it contain homogenusoly like 3*3,4*4 matrics
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
rows,coloums=arr.shape
print(f"Rows:{rows}\nColoums:{coloums}")
# while it print 2 values where 1st represent "rows" and 2nd value represent "coloums"

Rows:3
Coloums:3


In [11]:
arr = np.array([1, 2, 3, 4])
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [12]:
#size is the function used to print size by counting each element in the array 
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr.size)

9


In [13]:
# 1. numpy.zeros() – Create an Array of Zeros
# The zeros() function creates an array filled with zeroes.
# numpy.zeros(shape, dtype=float)
# shape: Specifies the shape of the array (e.g., (rows, cols) for 2D arrays).
# dtype: Specifies the data type (default is float).
arr=np.zeros((3,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
# 2. numpy.ones() – Create an Array of Ones
# The ones() function creates an array filled with ones.
# Syntax:numpy.ones(shape, dtype=float)
# shape: Specifies the dimensions of the array.
# dtype: Specifies the data type (default is float).
arr=np.ones((3,4),dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
# 3. numpy.eye() – Create an Identity Matrix
# The eye() function creates an identity matrix, which has 1s on the main diagonal and 0s elsewhere.
# numpy.eye(N, M=None, k=0, dtype=float)
# N: Number of rows.
# M: Number of columns (if not given, it's set equal to N).
# k: Diagonal offset (k=0 for main diagonal, k>0 for above, k<0 for below).
# dtype: Specifies the data type.
arr=np.eye(3,3,0,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
# indexing in the arrays same as the indexing in lists but in lists we need to mention that lis[0][1] 
# where in arrays we need to mention with the array[0,1]
import numpy as np
lis=[10,20,30,40,50,60,70,80,90,110,120,130]
arr=np.array(lis)
print(arr.size)
re_arr=arr.reshape(3,2,2)
print(re_arr[0,0],re_arr[0,1])

12
[10 20] [30 40]


In [17]:
re_arr

array([[[ 10,  20],
        [ 30,  40]],

       [[ 50,  60],
        [ 70,  80]],

       [[ 90, 110],
        [120, 130]]])

In [18]:
for i in range(0,2):
    print(f"{re_arr[i,i]}")

[10 20]
[70 80]


In [19]:
import numpy as np
lis=[2,3,5,2,6,3,2,5,2,8,5,3,9,4]
arr=np.array(lis)

In [20]:
row=arr.reshape(2,7)
dime=row.ndim
dime

2

In [21]:
np.sort(row)

array([[2, 2, 2, 3, 3, 5, 6],
       [2, 3, 4, 5, 5, 8, 9]])

In [22]:
import numpy as np
list1=[1,2,3,4,5,6,7,8,9,10]
array=np.array(list1)
array.resize(3,4)
print(array)
# ranks=np.linalg.rank(array)
# print(ranks)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]]


1. Array Creation and Manipulat
   1) np.array(): Create an array from a list or other data structures.
   2) np.arange(): Create an array with a range of values (like range() in Python).
   3) np.linspace(): Create an array of evenly spaced values over a specified range.
   4) np.zeros(): Create an array filled with zeros.
   5) np.ones(): Create an array filled with ones.
   6) np.empty(): Create an uninitialized array.
   7) np.eye(): Create a 2D identity matrix.
   8) np.full(): Create an array filled with a constant value.
   9) np.reshape(): Change the shape of an array.
   10) np.ravel(): Flatten an array into one dimension.
   11) np.concatenate(): Join two or more arrays.
   12) np.split(): Split an array into multiple sub-arrays.
   13) np.vstack(): Stack arrays in sequence vertically (row wise).
   14) np.hstack(): Stack arrays in sequence horizontally (column wise).

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print("1)",arr)
print()
arr1=np.arange(1,10,2)
print("2)",arr1)
print()
arr2=np.linspace(0,10,3)
print("3)",arr2)
print()
arr3=np.zeros((3,3),dtype=int)
print("4)",arr3)
print()
arr4=np.ones((3,3),dtype=int)
print("5)",arr4)
print()
arr5=np.empty((3,3))
print("6)",arr5)
print()
arr6=np.eye(3,3)
print("7)",arr6)
print()
arr7=np.full((3,3),3.14)
print("8)",arr7)
print()
temp=np.array([10,20,30,40,50,60,70,80,90])
arr8=np.reshape(temp,(3,3))
print("9)",arr8)
print()
arr9=np.ravel(arr8)
print("10)",arr9)
print()
arr10=arr8.flatten()
print("11)",arr10)
print()
arr11=np.concatenate(arr8)
print("12)",arr11)
print()
arr12=np.split(arr10,3)
print("13)",arr12)
print()
arr13=np.vstack(arr8)
print("14)",arr13)
print()
arr14=np.hstack(arr13)
print("15",arr14)

1) [1 2 3 4 5 6 7 8]

2) [1 3 5 7 9]

3) [ 0.  5. 10.]

4) [[0 0 0]
 [0 0 0]
 [0 0 0]]

5) [[1 1 1]
 [1 1 1]
 [1 1 1]]

6) [[0.0000e+000 0.0000e+000 0.0000e+000]
 [0.0000e+000 0.0000e+000 1.4427e-320]
 [0.0000e+000 0.0000e+000 0.0000e+000]]

7) [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

8) [[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]

9) [[10 20 30]
 [40 50 60]
 [70 80 90]]

10) [10 20 30 40 50 60 70 80 90]

11) [10 20 30 40 50 60 70 80 90]

12) [10 20 30 40 50 60 70 80 90]

13) [array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]

14) [[10 20 30]
 [40 50 60]
 [70 80 90]]

15 [10 20 30 40 50 60 70 80 90]


In [50]:
# 📌 1. NumPy Array Creation & Properties
# 1️⃣ Create a NumPy array from a list [10, 20, 30, 40, 50].
# 2️⃣ Create a 3x3 matrix filled with zeros.
# 3️⃣ Create a 5x5 matrix filled with ones.
# 4️⃣ Create an array of numbers from 1 to 10 with a step of 2.
# 5️⃣ Create a 4x4 identity matrix.
# 6️⃣ Create an array of 10 random numbers between 0 and 1.
# 7️⃣ Check the shape and size of a given NumPy array.
# 8️⃣ Convert a 1D array into a 2D array.
# 9️⃣ Create an array of even numbers between 10 and 50.
# 🔟 Find the datatype of elements in a NumPy array.
import numpy as np
array1=np.array([10,20,30,40,50])
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]]


In [52]:
array2=np.zeros((3,3),dtype=int)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]]


In [54]:
array3=np.ones((5,5),dtype=int)
print(array3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [56]:
array4=np.arange(0,10,2)
array4

array([0, 2, 4, 6, 8])

In [58]:
import numpy as np
array5=np.eye(5,5,0)
print(array5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [60]:
array6=np.random.randint(0,10,size=(5,5))
print(array6)

[[1 1 0 0 1]
 [0 0 4 4 6]
 [0 6 9 6 7]
 [9 1 3 6 2]
 [3 7 2 7 5]]


In [62]:
print(array6.shape)
print(array6.size)

(5, 5)
25


In [64]:
array8=np.array([10,20,30,40,50,60,70,80,90])
arr_8=array8.reshape(3,3)
arr_8

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [66]:
even=[i for i in range(10,51) if i%2==0]
array9=np.array(even)
print(array8)

[10 20 30 40 50 60 70 80 90]


In [68]:
array10=np.array([10,20,30,40.0,50])
print(array10.dtype)

float64


In [70]:
# 📌 2. NumPy Indexing & Slicing
# 1️⃣ Extract the first row of a 3x3 matrix.
# 2️⃣ Extract the last column of a 4x4 matrix.
# 3️⃣ Reverse a NumPy array (e.g., [1, 2, 3] → [3, 2, 1]).
# 4️⃣ Replace all even numbers in an array with -1.
# 5️⃣ Replace all odd numbers in an array with 0.
# 6️⃣ Select only numbers greater than 5 in an array.
# 7️⃣ Set all elements in a NumPy array greater than 10 to 0.
# 8️⃣ Change the shape of a NumPy array without modifying its data.

In [72]:
array1=np.array([10,20,30,40,50,60,70,80,90])
arr_1=array1.reshape(3,3)
print(arr_1[:1,:])

[[10 20 30]]


In [84]:
array2=np.random.randint(0,10,size=(4,4))
print(array2)
print(array2[:,-1])

[[2 3 8 0]
 [7 3 5 3]
 [7 2 2 4]
 [1 1 6 6]]
[0 3 4 6]


In [86]:
array3=np.array([10,20,30,40])
print(array3[::-1])

[40 30 20 10]


In [88]:
arr4=np.arange(1,10)
arr_4=arr4.reshape(3,3)
arr_4[arr_4%2==0]=-1
print(arr_4)

[[ 1 -1  3]
 [-1  5 -1]
 [ 7 -1  9]]


In [92]:
arr5=np.arange(1,10).reshape(3,3)
arr5[arr5%2!=0]=0
print(arr5)
print(arr5)

[[0 2 0]
 [4 0 6]
 [0 8 0]]
[[0 2 0]
 [4 0 6]
 [0 8 0]]


In [82]:
s

NameError: name 's' is not defined

In [94]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
harr=np.sum((arr,arr1))

In [96]:
harr

21

In [102]:
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
value=arr+arr1
add_val=np.add(arr,arr1)
print(value)
print(add_val)

[5 7 9]
[5 7 9]


In [106]:
arr=np.array([[1,7,3],[4,5,6]])
sums=np.sort(arr,axis=1)
sums

array([[1, 3, 7],
       [4, 5, 6]])

In [108]:
arr.put(1,7)
print(arr)

[[1 7 3]
 [4 5 6]]


In [110]:
import numpy as np
arr=np.random.randint(1,10,size=(3,3))

In [112]:
arr

array([[4, 7, 4],
       [4, 1, 4],
       [2, 6, 7]])

In [114]:
arr.max(axis=0)

array([4, 7, 7])

In [116]:
arr.max(axis=1)

array([7, 4, 7])

In [118]:
arr.min(axis=1)

array([4, 1, 2])

In [120]:
arr.min(axis=0)

array([2, 1, 4])

### Practice of NUMPY

In [1]:
import numpy as np
a=[10,20,30,40,50]
np.array(a)

array([10, 20, 30, 40, 50])

In [2]:
# type casting
b=[10.3,11,22,33,'Name']
print(np.array(b))

['10.3' '11' '22' '33' 'Name']


In [3]:
c=np.array([[10,20,30],[40,50,60]])
d=np.array([[11,12,13],[14,15,16]])
e=c*d
# f=c.dot(d)

In [4]:
e

array([[110, 240, 390],
       [560, 750, 960]])

In [9]:
f

NameError: name 'f' is not defined

In [13]:
c+d

array([[21, 32, 43],
       [54, 65, 76]])

In [15]:
np.concatenate(c,d)

TypeError: only integer scalar arrays can be converted to a scalar index

In [93]:
c

array([[10, 20, 30],
       [40, 50, 60]])

In [95]:
d

array([[11, 12, 13],
       [14, 15, 16]])

In [97]:
np.concatenate(c,d)

TypeError: only integer scalar arrays can be converted to a scalar index